# configuration file, v1.0.0-alpha.

fireworks:
  explode-fail-rate: 30 # how frequently should fireworks fail and don't work. 0 - 100 (%)
  boost-fail-rate: 40 # how frequently should fireworks fail (reduce boost) when use elytra.

dynamite:
  early-explode-rate: 50