name: FireworksMechanics
version: '${project.version}'
main: "top.cmarco.fireworksmechanics.FireworksMechanics"
api-version: '1.13'
authors: [CMarco_, Mardroide]
description: "SpigotMC plugin to add new explosive mechanics to fireworks and TNTs."

